lang_abr = {
    "Arabic": "ara",
    "Basque": "eus",
    "Bulgarian": "bul",
    "Catalan": "cat",
    "Chinese": "zho",
    "Croatian": "hrv",
    "Czech": "ces",
    "Danish": "dan",
    "Dutch": "nld",
    "English": "eng",
    "Estonian": "est",
    "Finnish": "fin",
    "French": "fra",
    "German": "deu",
    "Greek": "ell",
    "Hungarian": "hun",
    "Irish": "gle",
    "Italian": "ita",
    "Japanese": "jpn",
    "Latin": "lat",
    "Latvian": "lav",
    "Lithuanian": "lit",
    "Maltese": "mlt",
    "Norwegian Bokmål": "nob",
    "Polish": "pol",
    "Portuguese": "por",
    "Romanian": "ron",
    "Russian": "rus",
    "Serbian Latin": "srp",
    "Slovak": "slk",
    "Slovene": "slv",
    "Spanish": "spa",
    "Swedish": "swe",
    "Turkish": "tur",
    "Ukrainian": "ukr",
    "Vietnamese": "vie"
}

langs_multiran = {
    "ara": "10",
    "eus": "68",
    "bul": "15",
    "cat": "53",
    "zho": "17",
    "hrv": "8",
    "ces": "16",
    "dan": "22",
    "nld": "24",
    "eng": "1",
    "est": "26",
    "fin": "36",
    "fra": "4",
    "deu": "3",
    "ell": "38",
    "hun": "42",
    "gle": "49",
    "ita": "23",
    "jpn": "28",
    "lat": "37",
    "lav": "27",
    "lit": "12",
    "mlt": "78",
    "nob": "30",
    "pol": "14",
    "por": "11",
    "ron": "13",
    "rus": "2",
    "srp": "114",
    "slk": "60",
    "slv": "67",
    "spa": "5",
    "swe": "29",
    "tur": "32",
    "ukr": "33",
    "vie": "21"
}

lang_abr_reverso = {
    "Arabic": "ara",
    "Basque": "baq",
    "Bulgarian": "bul",
    "Catalan": "cat",
    "Chinese": "chi",
    "Croatian": "hrv",
    "Czech": "cze",
    "Danish": "dan",
    "Dutch": "dut",
    "English": "eng",
    "Estonian": "est",
    "Finnish": "fin",
    "French": "fra",
    "German": "ger",
    "Greek": "ell",
    "Hungarian": "hun",
    "Irish": "gle",
    "Italian": "ita",
    "Japanese": "jpn",
    "Latin": "lat",
    "Latvian": "lav",
    "Lithuanian": "lit",
    "Maltese": "mlt",
    "Norwegian Bokmål": "nor",
    "Polish": "pol",
    "Portuguese": "por",
    "Romanian": "rum",
    "Russian": "rus",
    "Serbian Latin": "src",
    "Slovak": "slo",
    "Slovene": "slv",
    "Spanish": "spa",
    "Swedish": "swe",
    "Turkish": "tur",
    "Ukrainian": "ukr",
    "Vietnamese": "vie"
}
